/* Write your T-SQL query statement below */
SELECT S.NAME
FROM SALESPERSON S
WHERE SALES_ID NOT IN(
    SELECT DISTINCT O.SALES_ID
    FROM COMPANY C
    JOIN ORDERS O
    ON C.COM_ID=O.COM_ID
    WHERE C.NAME='RED'
)